export { baseApi } from './baseApi'

export * from './authApi'
export * from './uploadApi'
export * from './testsApi'
export * from './usersApi'
export * from './accessApi'
export * from './paymentsApi'
export * from './reportsApi'
export * from './notificationsApi'
export * from './newsApi'
export * from './videosApi'
export * from './gamesApi'
export * from './ratingApi'
